### ISSUE TITLE
Which telegram module to install?

### ISSUE THREAD

**Issue by fhennies** [Simonx22/Google-Assistant-for-Telegram#1]
Used  telegram-0.0.1.tar.gz, get error:
`File "telegramassistant.py", line 21, in <module>
    from telegram.error import NetworkError, Unauthorized
ImportError: No module named 'telegram.error'`

**Comment by fhennies** [comment]
I also tried python_telegram_bot-10.0.1 without success (but different error message):

`File "telegramassistant.py", line 22, in <module>
    from telegram.ext import MessageHandler, Filters, Updater
  File "/home/Franz/.local/lib/python3.5/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher, DispatcherHandlerStop, run_async
  File "/home/Franz/.local/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 33, in <module>
    from telegram import TelegramError
ImportError: cannot import name 'TelegramError'`

**Comment by Simonx22** [comment]
You can take a look [here](https://github.com/JonnyHaystack/Google-Assistant-for-Telegram/blob/master/requirements.txt) to see the requirements.

@JonnyHaystack (since I don't know how else to contact you): Hey, I've seen that you forked and improved my repository. These changes look good to me and I look forward to having them in my repo. Do you maybe want to create a pull request?

**Comment by JonnyHaystack** [comment]
Yeah sure :smiley:

**Comment by fhennies** [comment]
Thanks, it helped.
